#!/bin/sh

set -e

echo "Running dd-trace-agent post-install with arguments: $@ ..."
case "$1" in
    configure)
        echo "Registering service dd-trace-agent"
        if command -v initctl > /dev/null 2>&1; then
            # use upstart if available
            set +e
            initctl reload-configuration
            if [[ $? -ne 0 ]] ; then
                echo "Skipping upstart registration as this system does not support it by default"
		exit 0
            fi
            set -e
        fi

        echo "Starting service dd-trace-agent"
        if command -v start > /dev/null 2>&1; then
            set +e
            stop dd-trace-agent
            start dd-trace-agent
            set -e
            echo "Post-install done"
            exit 0
        fi
        ;;
esac

# dh_installinit handles the configure phase for sysvinit systems

#DEBHELPER#
echo "Post-install done"
exit 0
