#!/bin/sh

echo "Running dd-trace-agent pre-remove with arguments $@ ..."
if command -v stop >/dev/null 2>&1; then
    stop dd-trace-agent || true
elif command -v invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d dd-trace-agent stop || true

    # Removing the service form startup (since it's not there anymore)
    update-rc.d -f dd-trace-agent disable >/dev/null 2>&1
    update-rc.d -f dd-trace-agent remove
else
    /etc/init.d/dd-trace-agent stop || true
fi

echo "Pre-remove done"
exit 0
