version: 2
jobs:
     build:
          working_directory: /go/src/github.com/DataDog/datadog-trace-agent
          resource_class: large

          docker:
               - image: circleci/golang:1.9.4

          steps:
               - checkout

               - run:
                    name: Install dependencies
                    command: |
                         go get -u github.com/Masterminds/glide/...
                         go get -u github.com/golang/lint/golint/...
                         glide install

               - run:
                    name: Test
                    command: |
                         $GOPATH/bin/golint ./cmd/trace-agent ./filters ./fixtures ./info ./quantile ./quantizer ./sampler ./statsd ./watchdog ./writer
                         go test ./...
