version: 2
jobs:
     build:
          working_directory: /go/src/github.com/DataDog/datadog-trace-agent
          resource_class: large

          docker:
               - image: circleci/golang:1.8

          steps:
               - checkout
               - run:
                    name: Install Ruby
                    command: sudo apt-get install rake

               - run:
                    name: Test
                    command: rake restore && rake ci
