// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collector.proto

/*
Package collector is a generated protocol buffer package.

It is generated from these files:
	collector.proto

It has these top-level messages:
	SendTracesRequest
	SendTracesResponse
	APITraceChunk
*/
package collector

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import agent "github.com/DataDog/datadog-trace-agent/internal/agent"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendTracesRequest struct {
	Chunks []*APITraceChunk `protobuf:"bytes,1,rep,name=chunks" json:"chunks,omitempty"`
}

func (m *SendTracesRequest) Reset()                    { *m = SendTracesRequest{} }
func (m *SendTracesRequest) String() string            { return proto.CompactTextString(m) }
func (*SendTracesRequest) ProtoMessage()               {}
func (*SendTracesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendTracesRequest) GetChunks() []*APITraceChunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

type SendTracesResponse struct {
}

func (m *SendTracesResponse) Reset()                    { *m = SendTracesResponse{} }
func (m *SendTracesResponse) String() string            { return proto.CompactTextString(m) }
func (*SendTracesResponse) ProtoMessage()               {}
func (*SendTracesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type APITraceChunk struct {
	Spans    []*agent.Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
	Hostname string        `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	TraceID  uint64        `protobuf:"varint,3,opt,name=traceID" json:"traceID,omitempty"`
}

func (m *APITraceChunk) Reset()                    { *m = APITraceChunk{} }
func (m *APITraceChunk) String() string            { return proto.CompactTextString(m) }
func (*APITraceChunk) ProtoMessage()               {}
func (*APITraceChunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *APITraceChunk) GetSpans() []*agent.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *APITraceChunk) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *APITraceChunk) GetTraceID() uint64 {
	if m != nil {
		return m.TraceID
	}
	return 0
}

func init() {
	proto.RegisterType((*SendTracesRequest)(nil), "collector.SendTracesRequest")
	proto.RegisterType((*SendTracesResponse)(nil), "collector.SendTracesResponse")
	proto.RegisterType((*APITraceChunk)(nil), "collector.APITraceChunk")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CollectorService service

type CollectorServiceClient interface {
	SendTraces(ctx context.Context, in *SendTracesRequest, opts ...grpc.CallOption) (*SendTracesResponse, error)
}

type collectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCollectorServiceClient(cc *grpc.ClientConn) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) SendTraces(ctx context.Context, in *SendTracesRequest, opts ...grpc.CallOption) (*SendTracesResponse, error) {
	out := new(SendTracesResponse)
	err := grpc.Invoke(ctx, "/collector.CollectorService/SendTraces", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CollectorService service

type CollectorServiceServer interface {
	SendTraces(context.Context, *SendTracesRequest) (*SendTracesResponse, error)
}

func RegisterCollectorServiceServer(s *grpc.Server, srv CollectorServiceServer) {
	s.RegisterService(&_CollectorService_serviceDesc, srv)
}

func _CollectorService_SendTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTracesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).SendTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collector.CollectorService/SendTraces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).SendTraces(ctx, req.(*SendTracesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "collector.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTraces",
			Handler:    _CollectorService_SendTraces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collector.proto",
}

func init() { proto.RegisterFile("collector.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xc3, 0xbf, 0x7f, 0xab, 0x9d, 0xc6, 0xa8, 0x1b, 0x0f, 0x84, 0x68, 0x82, 0x9c, 0xb8,
	0x14, 0x4c, 0xfd, 0x02, 0x9a, 0xe2, 0x81, 0x9b, 0x01, 0xaf, 0x1e, 0xa6, 0xcb, 0x04, 0x88, 0x74,
	0x17, 0x77, 0x07, 0x3f, 0xbf, 0x01, 0xa4, 0xad, 0x31, 0x1e, 0xdf, 0xbe, 0x5f, 0xde, 0xbe, 0x37,
	0x70, 0x21, 0x75, 0xd3, 0x90, 0x64, 0x6d, 0xa2, 0xd6, 0x68, 0xd6, 0x62, 0xb1, 0x7f, 0xf0, 0x1e,
	0xcb, 0x9a, 0xab, 0x6e, 0x1b, 0x49, 0xbd, 0x8b, 0x13, 0x64, 0x4c, 0x74, 0x19, 0x17, 0xc8, 0x58,
	0xe8, 0x72, 0xc5, 0x06, 0x25, 0xad, 0xb0, 0x24, 0xc5, 0x71, 0xad, 0x98, 0x8c, 0xc2, 0x26, 0x1e,
	0xa5, 0x6d, 0x51, 0x8d, 0x61, 0xc1, 0x33, 0x5c, 0xe5, 0xa4, 0x8a, 0xd7, 0x1e, 0xb6, 0x19, 0x7d,
	0x74, 0x64, 0x59, 0xdc, 0xc3, 0x5c, 0x56, 0x9d, 0x7a, 0xb7, 0xae, 0xe3, 0xcf, 0xc2, 0xe5, 0xda,
	0x8d, 0x0e, 0x1d, 0x9e, 0x5e, 0xd2, 0x01, 0xde, 0xf4, 0x40, 0xf6, 0xcd, 0x05, 0xd7, 0x20, 0x8e,
	0x63, 0x6c, 0xab, 0x95, 0xa5, 0xa0, 0x82, 0xf3, 0x1f, 0xb8, 0xb8, 0x83, 0x93, 0xfe, 0xef, 0x29,
	0x77, 0x19, 0x0d, 0x7d, 0xa2, 0xbc, 0x45, 0x95, 0x8d, 0x8e, 0xf0, 0xe0, 0xac, 0xd2, 0x96, 0x15,
	0xee, 0xc8, 0xfd, 0xe7, 0x3b, 0xe1, 0x22, 0xdb, 0x6b, 0xe1, 0xc2, 0xe9, 0xb0, 0x2a, 0x4d, 0xdc,
	0x99, 0xef, 0x84, 0xff, 0xb3, 0x49, 0xae, 0xdf, 0xe0, 0x72, 0x33, 0x55, 0xcc, 0xc9, 0x7c, 0xd6,
	0x92, 0x44, 0x0a, 0x70, 0xe8, 0x24, 0x6e, 0x8e, 0x36, 0xfc, 0x5a, 0xec, 0xdd, 0xfe, 0xe1, 0x8e,
	0x43, 0xb6, 0xf3, 0xe1, 0x58, 0x0f, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xc1, 0x6f, 0x69,
	0x8c, 0x01, 0x00, 0x00,
}
