
// Code generated by 'go run make.go'. DO NOT EDIT.

package info

import (
	"runtime"
	"strings"
)

func init() {
	Version = "111"
	GitCommit = "7acc5885"
	GitBranch = "gbbr/internal"
	BuildDate = "2018-11-28 13:41:41.829345549 +0100 CET m=+0.009863799"
	GoVersion = strings.TrimPrefix(runtime.Version(), "go")
}
