
// Code generated by 'go run make.go'. DO NOT EDIT.

package info

import (
	"runtime"
	"strings"
)

func init() {
	Version = "0.99.0"
	GitCommit = "24901b8a"
	GitBranch = "bmermet/collector"
	BuildDate = "2018-12-13 09:39:49.262417 +0100 CET m=+0.010135958"
	GoVersion = strings.TrimPrefix(runtime.Version(), "go")
}
