#!/usr/bin/expect -f
#
# rpmsign-batch.expect : expect powered rpm signing command
#

set passphrase $env(RPM_SIGNING_PASSPHRASE)

spawn rpm --addsign /go/src/github.com/DataDog/raclette/RPMS/x86_64/*.rpm
expect -exact "Enter pass phrase: "
send -- "$passphrase\r"
expect eof
