dd_url: https://app.datadoghq.com
api_key: api_key_test
hostname: mymachine
proxy:
  https: https://user:password@proxy_for_https:1234
use_dogstatsd: yes
dogstatsd_port: 18125
dogstatsd_non_local_traffic: yes
log_level: debug
apm_config:
  enabled: false
  apm_dd_url: https://datadog.unittests
  env: test
  receiver_port: 18126
  apm_non_local_traffic: yes
  extra_sample_rate: 0.5
  max_traces_per_second: 5
  ignore_resources:
    - /health
    - /500
  obfuscation:
    elasticsearch:
      enabled: true
      keep_values:
        - user_id
        - category_id
    mongodb:
      enabled: true
      keep_values:
        - uid
        - cat_id
    http:
      remove_query_string: true
      remove_paths_with_digits: true
    remove_stack_traces: true
